- CHANGELOG.md
- docker.sh
- release_api_doc.sh
- release_app_config.sh
- release_authentication.sh
- release_events.sh
- release_logging.sh
- release_profile.sh
> Update base docker image when doing release.

- .github/workflows/detect-secrets.yaml
- .pre-commit-config.yaml
- CHANGELOG.md
- eventservice/api/categories.json
- eventservice/api/controllers/events.py
- eventservice/api/utils/db.py
- eventservice/events.yaml
- release_base_script.sh
This PR creates a new variant of the Events Building Block for supporting group events. This new Group Events Building Block will be called by the Groups Building Block.
**Fixes #591**
[comment]: # (If you're unsure about any of these, don't hesitate to …
> Add support for group events

- CHANGELOG.md
- eventservice/api/controllers/events.py
> events group authorization

- CHANGELOG.md
- eventservice/events.yaml
> add userauth to events yml file

- CHANGELOG.md
- contributions/api/contributions_rest_service.py
- contributions/api/controllers/contributions.py
- contributions/api/utils/query_params.py
Added strict validation in Contributions building block and simplified the query.
_Please select a …
> Added strict validation

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
- contributions/catalog/webapps/templates/contribute/home.html
Previously we had the issue of data loading happens after clicking "talent" or "capability". However, we expect to see data to display right after loading.
[comment]: # (If you're unsure about …
> Fix  bug of 'showall' display issue

- CHANGELOG.md
- CODEOWNERS
Updated CODEOWNERS file.
**Fixes #631** …
> Update CODEOWNERS file

- CHANGELOG.md
- eventservice/events.yaml
> update event yaml file to add createdByGroupId field

- CHANGELOG.md
- eventservice/api/controllers/events.py
> fix dateformat issue in events GET /events/<id>

- CHANGELOG.md
- contributions/catalog/catalog_rest_service.py
- contributions/catalog/controllers/contribute.py
- contributions/catalog/webapps/templates/contribute/contribute.html
[comment]: # (To select an option, please put an 'x' in the …
> add autocomplete feature for admin names

- CHANGELOG.md
- contributions/catalog/models/capability_utilities.py
- contributions/catalog/models/talent_utilities.py
use uuid4 to generate id for talent and capability as one of fields in the json 
_Please select a …
> add uuid for capability and talent

- CHANGELOG.md
- contributions/catalog/catalog_rest_service.py
- contributions/catalog/controllers/auth.py
- contributions/catalog/controllers/contribute.py
how to test:
- after seeing the homepage without logging in, try to access the .../contribute/create url
- the expected behavior is to take back to login page, instead of showing the submit page 
- once we login in, then we should be able to see the submit page well
_Please give your idea …
> add login check decorator

- CHANGELOG.md
- contributions/api/models/capabilities/capability.py
- contributions/api/models/contribution.py
- contributions/api/utils/datasetutils.py
> fixed status in contribution

- CHANGELOG.md
- contributions/api/controllers/contributions.py
- contributions/api/utils/rest_handlers.py
- contributions/contribution.yaml
> added okay end point

- CHANGELOG.md
- eventservice/events.yaml
> add isGroupPrivate to Events Schema

- CHANGELOG.md
- eventservice/README.md
- eventservice/api/utils/db.py
> remove db index sponsor field

- CHANGELOG.md
- eventservice/api/controllers/configs.py
- eventservice/api/controllers/events.py
- eventservice/api/utils/group_auth.py
- eventservice/api/utils/query_params.py
> Event api key auth 683/684

- CHANGELOG.md
- eventservice/events.yaml
> add isEventFree field to Events Building Block yaml file

- CHANGELOG.md
- eventservice/events.yaml
> 706 update event schema description

- CHANGELOG.md
- eventservice/api/controllers/events.py
> group auth on get event by event id endpoint

- CHANGELOG.md
- eventservice/api/controllers/events.py
- eventservice/api/utils/group_auth.py
> Group authorize put event by eventid

- CHANGELOG.md
- eventservice/api/controllers/events.py
- eventservice/api/utils/group_auth.py
> 700 Group authorize delete event by eventid

- CHANGELOG.md
- eventservice/api/controllers/events.py
- eventservice/api/utils/group_auth.py
> 701 Group authorize patch event by eventid

- CHANGELOG.md
- eventservice/api/controllers/events.py
- eventservice/api/utils/group_auth.py
> add group authorization get image by eventid

- CHANGELOG.md
- eventservice/api/utils/query_params.py
> 732 fix title search with private userkey

- CHANGELOG.md
- eventservice/api/controllers/events.py
> 746 fix get endpoint with user auth key

- CHANGELOG.md
- contributions/catalog/controllers/config.py
- contributions/catalog/controllers/contribute.py
- contributions/catalog/webapps/templates/contribute/contribution_details.html
- contributions/catalog/webapps/templates/contribute/home.html
> fixed hard coded url

- CHANGELOG.md
- contributions/catalog/catalog_rest_service.py
- contributions/catalog/controllers/config.py
- contributions/catalog/controllers/contribute.py
> 782 catalog bug fixes

- CHANGELOG.md
- contributions/catalog/Dockerfile
- contributions/catalog/gunicorn.config.py
- release_contributions_catalog.sh
> Add Catalog release script and change default port and URL prefix.

- CHANGELOG.md
- appconfigservice/api/controllers/app.py
- appconfigservice/appconfig.yaml
Adding /ok public endpoint for healthcheck. This public endpoint returns a success message with HTTP 200 response.
**Fixes #754 **
_Please select a relevant …
> Edits for /ok endpoint

- CHANGELOG.md
- eventservice/README.md
- eventservice/api/controllers/events.py
- eventservice/api/utils/jsonutils.py
- eventservice/api/utils/mongoutils.py
Add more information of the events like tags, title, and description when POST, PUT, DELTE, and PATCH.
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to …
> 822 add details to event logs

- CHANGELOG.md
- profileservice/api/controllers/profiles.py
Made the string comparison more secure using hmac.compare_digest() method. Some comparisons that are not string comparison, such as `len(data_list) == 0` or `pii_dataset == None` have remained as they were
[comment]: # (To select an option, please put an 'x' in the …
> added secure string comparison)

- CHANGELOG.md
- eventservice/api/controllers/events.py
- eventservice/api/utils/group_auth.py
- eventservice/api/utils/query_params.py
Added a method to check if the users belongs to all_group_event by parsing the token. If the user is in the group, the user can get or delete the group event.
[comment]: # (If you're unsure about …
> 847 fix event bb get delete for admin app

- CHANGELOG.md
- CODEOWNERS
> 726 update codeowners file

- CHANGELOG.md
- eventservice/events.yaml
> 846 update events bb api doc

- CHANGELOG.md
- eventservice/README.md
- eventservice/api/events_rest_service.py
- eventservice/api/utils/query_params.py
- eventservice/events.yaml
> query by createdBy

- CHANGELOG.md
- eventservice/requirements.txt
> Fix build error in Events BB.

- CHANGELOG.md
- contributions/api/utils/mongoutils.py
This PR makes changes in mongoutils so as to output Authorization error (401) on GET on unpublished contributions.
**Fixes #826**
_Please select a relevant …
> 826 Error in Contributions GET for Talent and Capabilities

- CHANGELOG.md
- contributions/api/contributions_rest_service.py
- contributions/catalog/catalog_rest_service.py
- release_contributions.sh
OAuth Transport Lib error occurs when deploying the docker image as urls are http, instead of https within the docker container. This can be resolved using ProxyFix.
**Fixes #928**
[comment]: # (If you're unsure about any of these, don't hesitate to …
> 928 catalog transport error bug

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/talent_details.html
This PR displays "None" if some fields in Talent self certification is empty. 
**Fixes #913**
[comment]: # (To select an …
> Display self certification in talent details page 

- CHANGELOG.md
- contributions/api/utils/datasetutils.py
- contributions/catalog/controllers/contribute.py
- contributions/catalog/models/capability_utilities.py
- contributions/catalog/webapps/templates/contribute/contribute.html
Environment variable key and value are indexed by the following pattern : 
- environmentVariables_key_{{num_env}}_{{num_cap}} and 
- environmentVariables_value_{{num_env}}_{{num_cap}} 
where num_env and num_cap are 0 indexed.
**Fixes #921**
[comment]: # …
> 921 env var catalog

- CHANGELOG.md
- eventservice/api/controllers/configs.py
- eventservice/api/utils/group_auth.py
The variable ROKWIRE_GROUP_API_KEY changed to INTERNAL_API_KEY …
> changed rokwire_group_api_key to internal_api_key

- CHANGELOG.md
- contributions/api/models/capabilities/capability.py
- contributions/api/models/talents/talent.py
- contributions/api/utils/datasetutils.py
- contributions/catalog/controllers/contribute.py
- contributions/catalog/models/talent_utilities.py
- contributions/catalog/webapps/templates/contribute/contribute.html
- contributions/contribution.yaml
Added icon field to both capability and talent. You can test using the endpoint directly, NOT going through catalog, by just adding icon field in capability and talent json in contribution json
**Fixes #945 **
[comment]: # (If you're unsure about any of …
> Added icon to both capability and talent

- CHANGELOG.md
- appconfigservice/requirements.txt
- auth-middleware-test-svc/requirements.txt
- authservice/requirements.txt
- contributions/requirements.txt
- eventservice/requirements.txt
- lib/auth-middleware/auth_middleware/__init__.py
- lib/auth-middleware/setup.py
- profileservice/requirements.txt
> 935 security apply fix from dependabot alerts to the auth middleware library

- CHANGELOG.md
- eventservice/README.md
- eventservice/api/utils/query_params.py
- eventservice/events.yaml
> hybrid events

- CHANGELOG.md
- Dockerfile
> 991 security update swagger UI base docker image version

- .gitignore
- CHANGELOG.md
- contributions/catalog/webapps/static/css/style.css
- contributions/catalog/webapps/templates/contribute/capability_details.html
Hide sensitive data (environment variable value) in capability view page. Uses bootstrap eye icon for toggle.
**Fixes #950**
_Please select a relevant …
> 950 hide sensitive data view capability page

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
Added minimum user privacy level value 1 to talent form.
**Fixes #970**
[comment]: # (To select an option, please put an …
> 970 added minimum user privacy level value talent form

- CHANGELOG.md
- eventservice/api/controllers/events.py
- eventservice/api/events_rest_service.py
> allow group admins to operate group events

- CHANGELOG.md
- contributions/catalog/controllers/contribute.py
This PR fixes the contribution_details page when catalog cannot display a contribution. The @bp.route('/contributions/<contribution_id>', methods=['GET']) contribution_details() method is changed to reflect this.
To test this PR:
- go to url /contributions/<contribution_id> while logged out, and see the "Unauthorized" error message
- go to url /contributions/<contribution_id> while logged in, but with a wrong contribution_id, and see "no records found" error message
**Fixes #961**
_Please give your idea of how soon this pull …
> 961 show appropriate error messages catalog

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
This PR moves the "Add Capability or Talent" buttons to the bottom of the form.
The "Select contribution type" field is positioned above the "Contact Details" form fields on button click.
**Fixes #971** …
> 971 move add talent capability buttons to bottom

- CHANGELOG.md
- contributions/catalog/controllers/contribute.py
Page redirect is changed after a contribution edit. After a contribution edit, user is redirected to contribution details page if logged in.
**Fixes #976** …
> 976 user redirect to contribution view after edit

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
Changed add more fields button
**Fixes #975** …
> 975 updated add more fields button text

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribution_details.html
"Edit Contribution" button class type changed.
**Fixes #981**
[comment]: # (To select an option, please put an 'x' in the …
> 981 change edit button color

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
Added cancel button in edit page. This redirects to the contribution_details page without submitting the latest edits.
**Fixes #986**
_Please select a …
> 986 cancel button in edit page

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/capability_details.html
Changed UI for environment variables in capability view page. Environment variables key value pair is in single row.
**Fixes #993**
_Please select a relevant …
> 993 single line environment variables capability view

- CHANGELOG.md
- contributions/requirements.txt
Updated gevent version in contributions requirements.txt.
**Fixes #1003**
[comment]: # (To select an option, please put an …
> 1003 update gevent contributions

- CHANGELOG.md
- contributions/catalog/requirements.txt
Gevent version is updated in catalog/requirements.txt 
**Fixes #1007**
[comment]: # (To select an option, please put an …
> 1007 updated gevent in catalog

- CHANGELOG.md
- contributions/catalog/webapps/static/css/style.css
- contributions/catalog/webapps/templates/contribute/contribute.html
In contribute create and edit page, the environment variable key-value pairs and data deletion endpoint details api key-value pairs are displayed in single line (one row two column styling). The styles are present in style.css file.
**Fixes #989** …
> 989 contribute single line environment variables

- CHANGELOG.md
- Dockerfile
This PR updates individual Building Block API docs that we display through the API Doc Building Block. 
**Fixes #831** …
> 831 feature add documentation from all available building blocks to api doc

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/capability_details.html
Toggle eye-icon added to data deletion endpoint details in capability view page.
**Fixes #1010**
[comment]: # (To select …
> 1010 data deletion details not hidden

- CHANGELOG.md
- contributions/catalog/webapps/static/css/style.css
- contributions/catalog/webapps/templates/contribute/contribute.html
User confirmation before "Cancel" contribution is asked. Added a modal for user confirmation on "Cancel"
**Fixes #1022** …
> 1022 user confirmation before cancel in catalog

- CHANGELOG.md
- contributions/api/utils/datasetutils.py
- contributions/catalog/webapps/templates/contribute/contribute.html
Make environmentVariable key required if present. 
In the contribute.html data_validation() method (which is called in submit button), get all elements with the class name envvar-key. Iterate through the list and check if any is empty. Return False if empty.
In contribution/api/dataset_utils, check if key is non-empty.
Review and merge [PR#1030](https://github.com/rokwire/rokwire-building-blocks-api/pull/1030) before this.
**Fixes #1028**
_Please give your idea of how soon this pull request needs to be reviewed by selecting one …
> 1028 env variable key required if present

- CHANGELOG.md
- contributions/contribution.yaml
The PR fixes error when PUT is performed on a talent with null fields. The yaml file is changed to include nullable fields for talent.
**Fixes #949**
_Please …
> 949 error publishing certain contributions

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
Delete capability and "Delete Talent" buttons works in contribution-create page.
**Fixes #1009**
[comment]: # (To select …
> 1009 delete cap and talent button

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
Edit for database detail field in catalog form is fixed.
Added "loop.index" to get the correct capability in catalog edit page.
**Fixes #1048**
_Please …
> 1048 bug edit contribution database detail

- CHANGELOG.md
- contributions/api/models/capabilities/capability.py
Apibaseurl is set using set and get functions in class Capability.
**Fixes #1047**
[comment]: # (To select an option, …
> Set ApibaseUrl in catalog

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
open source url field not displayed when isopensource radio button is clicked in edit mode.
In catalog contribution/edit page, opensource url field is not being displayed when isOpenSource radio button value is "yes".
Added an onclick function on the input radio button to show/hide sourceurl field. MoveSelector method is added to move the "Select a contribution type" div accordingly.
**Fixes #1053**
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based …
> 1053 bug open source url field

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
Some divs were not closed correctly. Fixed that in this PR.
Added container div classes to separate sections in contribute form.
The footer spacing in contribute page is also rectified in this PR.
**Fixes #1079 #1081**
[comment]: # (If you're unsure …
> 1079 contribute create page div rearrangement

- CHANGELOG.md
- contributions/catalog/webapps/static/css/style.css
- contributions/catalog/webapps/templates/contribute/contribute.html
Contribute page styling updated.
Vertical alignment of radio buttons, text boxes and checkboxes are fixed.
Stylings fixed in contribute create and edit pages.
Styling for breadcrumbs yet to be updated (awaiting designer input for the same).
**Fixes #1087**
[comment]: # (To select an option, please put an 'x' in the applicable …
> 1087 vertical alignment in contribute page

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
Input validation for contribute/create page.
The type for each input field is specified.
Input types used are "text", "tel", "url" and "email".
**Fixes #1103**
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to …
> 1103 validation for form fields in UI

- CHANGELOG.md
- contributions/catalog/webapps/templates/contribute/contribute.html
Updated contribute page form field labels and placeholders.
Let me know if anything needs to be changed.
For now only contributions/create page form labels are changed.
**Fixes #1102**
[comment]: # (If you're unsure about any of these, don't hesitate to …
> 1102 fix form texts and placeholders

- CHANGELOG.md
- eventservice/Dockerfile
- eventservice/requirements.txt
> events BB dependencies updates

- .secrets.baseline
- CHANGELOG.md
- eventservice/README.md
- eventservice/api/categories.json
- eventservice/api/utils/db.py
- eventservice/events.yaml
> Update Event categories and subcategories list
